// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("GraphQLCS")]
[assembly: AssemblyProductAttribute("GraphQL.net")]
[assembly: AssemblyDescriptionAttribute("An implementation of Facebook's GraphQL for .NET and F#.")]
[assembly: AssemblyVersionAttribute("0.1.0")]
[assembly: AssemblyFileVersionAttribute("0.1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.1.0";
        internal const string InformationalVersion = "0.1.0";
    }
}
